# Generated by Django 4.1 on 2022-08-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0003_division_alter_team_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="nba.conference",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="nba.division",
            ),
        ),
    ]
