# Generated by Django 4.0.4 on 2022-05-04 18:08

from django.db import migrations


def seed(apps, schema_editor):
    Conference = apps.get_model('sprts', 'Conference')
    Team = apps.get_model('sprts', 'Team')
    Player = apps.get_model('sprts', 'Player')
    afc = Conference(name="afc")
    nfc = Conference(name="nfc")
    afc.save()
    nfc.save()

    titans = Team(conference=afc, name='Titans',
                  location='Tennessee', wins=12, losses=5)
    chiefs = Team(conference=afc, name='Chiefs',
                  location='Kansas City', wins=12, losses=5)
    bills = Team(conference=afc, name='Bills',
                 location='Buffalo', wins=11, losses=6)
    packers = Team(conference=nfc, name='Packers',
                   location='Green Bay', wins=13, losses=4)
    buccaneers = Team(conference=nfc, name='Buccaneers',
                      location='Tampa Bay', wins=13, losses=4)
    cowboys = Team(conference=nfc, name='Cowboys',
                   location='Dallas', wins=12, losses=5)
    titans.save()
    chiefs.save()
    bills.save()
    packers.save()
    buccaneers.save()
    cowboys.save()

    Player(team=titans, name='Julio Jones',
           position='WR', age=33, injured=True).save()
    Player(team=titans, name='Derrick Henry',
           position='RB', age=28, injured=False).save()
    Player(team=titans, name='Ryan Tannehill',
           position='QB', age=33, injured=False).save()
    Player(team=chiefs, name='JuJu Smith-Schuster',
           position='WR', age=25, injured=False).save()
    Player(team=chiefs, name='Clyde Edwards-Helaire',
           position='RB', age=23, injured=True).save()
    Player(team=chiefs, name='Patrick Mahomes',
           position='QB', age=26, injured=False).save()
    Player(team=bills, name='Julio Jones',
           position='WR', age=33, injured=True).save()
    Player(team=bills, name='Derrick Henry',
           position='RB', age=28, injured=False).save()
    Player(team=bills, name='Ryan Tannehill',
           position='QB', age=33, injured=False).save()
    Player(team=packers, name='JuJu Smith-Schuster',
           position='WR', age=25, injured=False).save()
    Player(team=packers, name='Clyde Edwards-Helaire',
           position='RB', age=23, injured=True).save()
    Player(team=packers, name='Patrick Mahomes',
           position='QB', age=26, injured=False).save()
    Player(team=buccaneers, name='Julio Jones',
           position='WR', age=33, injured=True).save()
    Player(team=buccaneers, name='Derrick Henry',
           position='RB', age=28, injured=False).save()
    Player(team=buccaneers, name='Ryan Tannehill',
           position='QB', age=33, injured=False).save()
    Player(team=cowboys, name='JuJu Smith-Schuster',
           position='WR', age=25, injured=False).save()
    Player(team=cowboys, name='Clyde Edwards-Helaire',
           position='RB', age=23, injured=True).save()
    Player(team=cowboys, name='Patrick Mahomes',
           position='QB', age=26, injured=False).save()


def fallow(apps, schema_editor):
    Player = apps.get_model('sprts', 'Player')
    Team = apps.get_model('sprts', 'Team')
    Conference = apps.get_model('sprts', 'Conference')
    Conference.objects.all().delete()
    Team.objects.all().delete()
    Player.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sprts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
